### PR TITLE
Fix terminal scrolling bug

### PR DESCRIPTION
**Pull request by sasdallas**
Hello, @pritamzope!

I opened this pull request to fix the broken method `console_scroll`. It should now work fine.
The terminal scrolling method is applied to the NEW KERNEL Terminal folder - let me know if there are any changes!

### CODE REVIEW

**Comment by sasdallas** [comment]
@pritamzope Do you have a reason why this was closed?

**Comment by pritamzope** [comment]
The code you have added is not working if i press UP/DOWN keys in VESA VBE code where all screen resolutions are printed. The screen is just randomly changing text.
Please add the scrolling code based on the key events and text changing.
Thanks

**Comment by sasdallas** [comment]
I will attempt to fix it later - thanks for the response

**Comment by sasdallas** [comment]
> The code you have added is not working if i press UP/DOWN keys in VESA VBE code where all screen resolutions are printed. The screen is just randomly changing text.
> Please add the scrolling code based on the key events and text changing.
> Thanks

Sorry for the wait, but unfortunately I don’t think I can help. I don’t believe my terminal scrolling code is suitable for anything other than text mode unfortunately. Have a great day, and thank you for this project!

**Pull request closed without merging**
